first_dbt_proj:
  outputs:
    dev:
      account: SZGRYIF-OH01976
      database: DBT_TEST
      password: Balabhadrakali@2025
      role: ACCOUNTADMIN
      schema: DBT_TESTSCHEMA
      threads: 1
      type: snowflake
      user: beena
      warehouse: COMPUTE_WH
  target: dev
